name: "Flake.lock: Update"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          nix-options: "--access-tokens github.com=${{ secrets.PRIVATE_FLAKE_INPUTS_TOKEN }}"
          pr-title: "Flake.lock: update inputs"
          pr-labels: |
            automated
