name: "Flake: Check"

on:
  push:
    branches: [ "main", "testing" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flake-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install nix
      uses: DeterminateSystems/nix-installer-action@v21
      with:
        determinate: false
        github-token: ${{ secrets.PRIVATE_FLAKE_INPUTS_TOKEN }}

    - name: Use nix cache
      uses: DeterminateSystems/magic-nix-cache-action@v13
      with:
        use-flakehub: false

    - name: Run statix (and show fixes if possible)
      shell: nix shell nixpkgs#statix nixpkgs#delta --command bash -e {0}
      run: |
        statix fix -d | grep -v '^$' | delta --paging never
        statix check .

    - name: Run deadnix
      run: nix run nixpkgs#deadnix -- --fail .

    - name: Check flake
      run: |
        if $(nix flake check --no-build --all-systems &>/dev/null); then
          echo "Flake check passed!" >> $GITHUB_STEP_SUMMARY
        else
          echo "Flake check failed, run `nix flake check` locally to see details." >> $GITHUB_STEP_SUMMARY
        fi

